export const jobs = [
    {
      id: 1,
      title: 'Senior Accountant',
      category: 'Accounting',
      salary: '$60,000 - $80,000',
      description: 'Manage financial records, ensure accuracy, and prepare financial reports.',
      location: 'New York, NY',
    },
    {
      id: 2,
      title: 'Junior Accountant',
      category: 'Accounting',
      salary: '$40,000 - $50,000',
      description: 'Assist in financial record keeping, accounts payable, and receivable tasks.',
      location: 'Los Angeles, CA',
    },
    {
      id: 3,
      title: 'Financial Analyst',
      category: 'Accounting',
      salary: '$70,000 - $90,000',
      description: 'Analyze financial data and create reports for management decision-making.',
      location: 'Chicago, IL',
    },
    {
      id: 4,
      title: 'Office Administrator',
      category: 'Administrative',
      salary: '$50,000 - $65,000',
      description: 'Manage office supplies, schedules, and handle day-to-day administrative tasks.',
      location: 'Miami, FL',
    },
    {
      id: 5,
      title: 'Executive Assistant',
      category: 'Administrative',
      salary: '$55,000 - $70,000',
      description: 'Assist top-level executives with scheduling, communications, and task management.',
      location: 'Houston, TX',
    },
    {
      id: 6,
      title: 'HR Specialist',
      category: 'Administrative',
      salary: '$60,000 - $75,000',
      description: 'Oversee recruitment, employee relations, and staff training programs.',
      location: 'Dallas, TX',
    },
    {
      id: 7,
      title: 'Delivery Driver',
      category: 'Driving',
      salary: '$40,000 - $50,000',
      description: 'Transport goods safely, ensuring timely delivery to various locations.',
      location: 'Phoenix, AZ',
    },
    {
      id: 8,
      title: 'Truck Driver',
      category: 'Driving',
      salary: '$50,000 - $65,000',
      description: 'Drive long distances, ensuring the safe and timely transport of goods.',
      location: 'Denver, CO',
    },
    {
      id: 9,
      title: 'Van Driver',
      category: 'Driving',
      salary: '$30,000 - $40,000',
      description: 'Drive a van to deliver packages, ensuring all deliveries are made on time.',
      location: 'San Francisco, CA',
    },
    {
      id: 10,
      title: 'Registered Nurse',
      category: 'Nursing & Care',
      salary: '$75,000 - $95,000',
      description: 'Provide patient care in hospitals, clinics, and home health settings.',
      location: 'Los Angeles, CA',
    },
    {
      id: 11,
      title: 'Home Health Aide',
      category: 'Nursing & Care',
      salary: '$30,000 - $45,000',
      description: 'Assist patients with daily living activities, including personal hygiene.',
      location: 'Austin, TX',
    },
    {
      id: 12,
      title: 'Clinical Nurse Specialist',
      category: 'Nursing & Care',
      salary: '$85,000 - $110,000',
      description: 'Specialize in providing expert clinical care and training for other nurses.',
      location: 'Seattle, WA',
    },
    {
      id: 13,
      title: 'Customer Service Representative',
      category: 'Customer Care',
      salary: '$35,000 - $45,000',
      description: 'Provide support to customers via phone, email, and chat.',
      location: 'Orlando, FL',
    },
    {
      id: 14,
      title: 'Call Center Manager',
      category: 'Customer Care',
      salary: '$50,000 - $65,000',
      description: 'Oversee call center operations, ensuring high-quality service to customers.',
      location: 'San Diego, CA',
    },
    {
      id: 15,
      title: 'Technical Support Specialist',
      category: 'Customer Care',
      salary: '$40,000 - $55,000',
      description: 'Provide technical support to customers, solving issues with products or services.',
      location: 'Dallas, TX',
    },
    {
      id: 16,
      title: 'Software Developer',
      category: 'Tech',
      salary: '$80,000 - $100,000',
      description: 'Develop software applications and solutions based on user requirements.',
      location: 'New York, NY',
    },
    {
      id: 17,
      title: 'Web Developer',
      category: 'Tech',
      salary: '$60,000 - $80,000',
      description: 'Design, build, and maintain websites and web applications.',
      location: 'Los Angeles, CA',
    },
    {
      id: 18,
      title: 'Database Administrator',
      category: 'Tech',
      salary: '$90,000 - $120,000',
      description: 'Manage and maintain database systems to ensure data integrity and security.',
      location: 'Chicago, IL',
    },
    {
      id: 19,
      title: 'Network Engineer',
      category: 'Tech',
      salary: '$70,000 - $90,000',
      description: 'Design, implement, and maintain network systems and infrastructure.',
      location: 'San Francisco, CA',
    },
    {
      id: 20,
      title: 'Front-End Developer',
      category: 'Tech',
      salary: '$65,000 - $85,000',
      description: 'Develop user-facing web applications using modern front-end technologies.',
      location: 'Seattle, WA',
    },
    {
      id: 21,
      title: 'Back-End Developer',
      category: 'Tech',
      salary: '$70,000 - $95,000',
      description: 'Build and maintain the server-side logic and databases for applications.',
      location: 'Dallas, TX',
    },
    {
      id: 22,
      title: 'IT Support Technician',
      category: 'Tech',
      salary: '$45,000 - $60,000',
      description: 'Provide IT support and troubleshooting for users within an organization.',
      location: 'Miami, FL',
    },
    {
      id: 23,
      title: 'Data Scientist',
      category: 'Tech',
      salary: '$90,000 - $120,000',
      description: 'Analyze complex data sets and build predictive models using statistical methods.',
      location: 'Washington, D.C.',
    },
    {
      id: 24,
      title: 'Nursing Assistant',
      category: 'Nursing & Care',
      salary: '$30,000 - $40,000',
      description: 'Assist nurses in providing basic patient care and monitor patients’ conditions.',
      location: 'Austin, TX',
    },
    {
      id: 25,
      title: 'Caregiver',
      category: 'Nursing & Care',
      salary: '$25,000 - $35,000',
      description: 'Provide personal care and companionship to elderly or disabled individuals.',
      location: 'Orlando, FL',
    },
    {
      id: 26,
      title: 'Medical Receptionist',
      category: 'Nursing & Care',
      salary: '$30,000 - $40,000',
      description: 'Schedule appointments, handle patient records, and manage office administrative tasks.',
      location: 'Phoenix, AZ',
    },
    {
      id: 27,
      title: 'Customer Support Associate',
      category: 'Customer Care',
      salary: '$35,000 - $45,000',
      description: 'Help customers resolve issues with products and services via phone or email.',
      location: 'Chicago, IL',
    },
    {
      id: 28,
      title: 'Field Technician',
      category: 'Tech',
      salary: '$45,000 - $60,000',
      description: 'Install, troubleshoot, and maintain technical equipment on-site for clients.',
      location: 'Los Angeles, CA',
    },
    {
      id: 29,
      title: 'Content Moderator',
      category: 'Tech',
      salary: '$35,000 - $50,000',
      description: 'Monitor and review user-generated content on digital platforms for compliance.',
      location: 'New York, NY',
    },
    {
      id: 30,
      title: 'IT Manager',
      category: 'Tech',
      salary: '$95,000 - $120,000',
      description: 'Lead IT department, overseeing network infrastructure, data security, and technology solutions.',
      location: 'Miami, FL',
    }
  ];
  